const { src, dest } = require(`gulp`);
const { plumber, twig, htmlmin, w3cHtmlValidator } = require(`gulp-load-plugins`)();

const html = () => src(`source/twig/pages/**/*.twig`)
	.pipe(plumber())
	.pipe(twig())
	.pipe(htmlmin({
		collapseBooleanAttributes: true,
		collapseWhitespace: true,
		decodeEntities: true,
		html5: true,
		includeAutoGeneratedTags: false,
		minifyCSS: true,
		minifyJS: true,
		processConditionalComments: true,
		quoteCharacter: `"`,
		removeComments: true,
		removeEmptyAttributes: true,
		removeRedundantAttributes: true,
		removeScriptTypeAttributes: true,
		removeStyleLinkTypeAttributes: true,
		trimCustomFragments: true,
		useShortDoctype: true
	}))
	.pipe(dest(`build`))
	.pipe(w3cHtmlValidator())
	.pipe(w3cHtmlValidator.reporter());

module.exports = html;
